inherit_from:
  - .rubocop_rspec.yml

##
# Standard based Rubocop config.
# - https://github.com/testdouble/standard
# - https://github.com/testdouble/standard#usage-via-rubocop
# - https://evilmartians.com/chronicles/rubocoping-with-legacy-bring-your-ruby-code-up-to-standard
#
require:
  ##
  # Rubocop for RSpec files.
  # - https://github.com/rubocop/rubocop-rspec
  #
  - rubocop-rspec
  ##
  # Rubocop cops for common performance issues.
  # - https://github.com/rubocop/rubocop-performance
  #
  # NOTE: `rubocop-performance` is automatically bundled with Standard.
  # - https://github.com/standardrb/standard
  #
  - rubocop-performance
  ##
  # RuboCop cops that detect the use of magic numbers.
  # - https://github.com/meetcleo/rubocop-magic_numbers
  #
  # TODO: Leave explanation to every `MagicNumbers` cops complaints.
  # NOTE: Do NOT forget to uncomment `MagicNumbers` custom configs.
  # - rubocop-magic_numbers
  ##
  # RuboCop cops that enforce Ruby gem packaging best practices.
  # - https://github.com/utkarsh2102/rubocop-packaging
  #
  - rubocop-packaging
  ##
  # Rubocop cops for common thread safety issues.
  # - https://github.com/covermymeds/rubocop-thread_safety
  #
  # TODO: Leave explanation to every `ThreadSafety/InstanceVariableInClassMethod`.
  # - https://github.com/covermymeds/rubocop-thread_safety/blob/master/spec/rubocop/cop/thread_safety/instance_variable_in_class_method_spec.rb
  # - https://workingwithruby.com/wwrt/good_oo
  #
  # - rubocop-thread_safety
  ##
  # NOTE: Custom Standard cop that should be loaded before `config/base.yml`.
  # - https://github.com/standardrb/standard-custom/blob/main/lib/standard/cop/block_single_line_braces.rb
  #
  - standard/cop/block_single_line_braces

inherit_gem:
  standard: config/base.yml

AllCops:
  ##
  # https://github.com/testdouble/standard#how-do-i-specify-a-ruby-version-what-is-supported
  #
  TargetRubyVersion: 2.7

  Exclude:
    ##
    # NOTE: Excludes vendor from linting. Needed by GitHub Actions.
    # - https://github.com/rubocop/rubocop/issues/9832
    # - https://github.com/rubocop/rubocop/issues/9832#issuecomment-873398952
    #
    - vendor/**/*

    ##
    # NOTE: Excludes dependencies from linting.
    #
    - lib/convenient_service/dependencies/**/*

##
# NOTE: Forces to use `# frozen_string_literal: true` in every Ruby file.
# - https://docs.rubocop.org/rubocop/cops_style.html#stylefrozenstringliteralcomment
#
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always_true

# MagicNumbers:
#   Exclude:
#     ##
#     # NOTE: Excludes the following files/folders from linting magic numbers.
#     # - https://github.com/meetcleo/rubocop-magic_numbers
#     # - https://docs.rubocop.org/rubocop/configuration.html#includingexcluding-files
#     #
#     - Rakefile
#     - benchmark/**/*
#     - spec/**/*
#     - test/**/*
