#!/usr/bin/env bash

##
# `rk' is an "alias" for `bundle exec rake'.
#

##
# NOTE: Forces the shell to exit immediately if any of its commands return a non-zero status.
# https://www.gnu.org/software/bash/manual/bash.html#The-Set-Builtin
#
set -e

##
# NOTE: Prints empty line.
#
echo

##
# NOTE: Prints original command in bold blue color.
# https://stackoverflow.com/a/69648792/12201472
#
echo -e "\033[1;34mbundle exec rake $@\033[0m"

##
# NOTE: Actually executes the command.
#
# NOTE: `$@' forwards all arguments.
# https://stackoverflow.com/a/3898681/12201472
#
bundle exec rake $@
