# frozen_string_literal: true

require "convenient_service"

##
# Non standard plugins.
#
ConvenientService.require_assigns_attributes_in_constructor_using_active_model_attribute_assignment
ConvenientService.require_assigns_attributes_in_constructor_using_dry_initializer
ConvenientService.require_has_attributes_using_active_model_attributes
ConvenientService.require_has_result_params_validations_using_active_model_validations
ConvenientService.require_has_result_params_validations_using_dry_validation
ConvenientService.require_development_tools

ConvenientService.require_rspec_extentions

ConvenientService.require_standard_examples
