##
# @author Marian Kostyk <mariankostyk13895@gmail.com>
# @license LGPLv3 <https://www.gnu.org/licenses/lgpl-3.0.html>
##

##
# NOTE: Tmuxinator config options.
# - https://github.com/tmuxinator/tmuxinator#create-a-project
#
name: convenient_service
root: .

on_project_start:
  - task editor:open
  - task docker:start
  - task github:open

windows:
  - main:
      layout: even-vertical
      root: .
      panes:
        - RUBY_ENGINE=ruby RUBY_ENGINE_VERSION=2.7 task docker:bash
        - RUBY_ENGINE=ruby RUBY_ENGINE_VERSION=3.4 task docker:bash
        - git status
  - api_docs:
      layout: even-vertical
      root: .
      panes:
        - task docs:server:open
        - task docs:missed
